image: golang:1.16-buster

stages:
  - checks
  - release

test:
  stage: checks
  script:
    - go test -v -cover ./...
  only:
    - tags
    - /^trunk$/
    - web
    - merge_requests

release:
  stage: release
  image: registry.gitlab.com/juhani/go-semrel-gitlab:v0.21.1
  script:
    - ls -la
  when: manual
  only:
    - /^trunk$/
